//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public int pid { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Street_Number { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Country { get; set; }
        public string Postal_Code { get; set; }
        public Nullable<long> Phone_Number { get; set; }
        public string email { get; set; }
    }
}
